#!/usr/bin/env python3
"""Generate seed-store.sql from the migrated Wix content in _source/.

Idempotent: re-running the generated SQL upserts by slug/key rather than duplicating.
"""
import json, os, re

ROOT = os.path.dirname(os.path.abspath(__file__))
os.chdir(ROOT)

prods = json.load(open("_source/products.json", encoding="utf-8"))
man = json.load(open("_source/image-manifest.json", encoding="utf-8"))

def q(s):
    """Quote a SQL string literal (None -> NULL)."""
    if s is None:
        return "null"
    return "'" + str(s).replace("'", "''") + "'"

def arr(items):
    """Quote a Postgres text[] literal."""
    if not items:
        return "'{}'"
    inner = ",".join('"' + str(i).replace("\\", "\\\\").replace('"', '\\"') + '"' for i in items)
    return "'{" + inner + "}'"

def clean(s):
    """Normalise text scraped from Wix: nbsp -> space, collapse runs, trim."""
    if s is None:
        return None
    s = s.replace(" ", " ").replace("​", "")
    return re.sub(r"[ \t]+", " ", s).strip()

def notes_for(slug):
    try:
        md = open(f"_source/pages/{slug}.md", encoding="utf-8").read()
    except FileNotFoundError:
        return []
    # price line may read "$220.00Price" or "From $260.00Sale Price"
    m = re.search(r"## NOTES(.*?)\$[\d.,]+\s*(?:Sale\s*)?Price", md, re.S)
    if not m:
        return []
    SKIP = {"price", "from", "starting at", "sale price"}
    out = []
    for l in m.group(1).splitlines():
        t = clean(l)
        if not t or "$" in t or t.lower() in SKIP:
            continue
        out.append(t)
    return out[:4]

out = ["-- Studio Maçon — seed store content (generated by make_seed.py; safe to re-run)",
       "-- Run AFTER schema-store.sql.", "", "begin;", ""]

# ---------- products ----------
out.append("-- ===== products =====")
for i, p in enumerate(prods):
    slug = p["slug"]
    if not man.get(slug):
        continue
    price = p.get("price")
    out.append(
        "insert into public.store_products "
        "(slug,name,price,description,notes,collection,status,quantity,sort_order) values ("
        f"{q(slug)},{q(clean(p['name']))},{price if price else 'null'},{q(clean(p.get('desc')))},"
        f"{arr(notes_for(slug))},'perennial','live',null,{i})\n"
        "on conflict (slug) do update set "
        "name=excluded.name, price=excluded.price, description=excluded.description, "
        "notes=excluded.notes, sort_order=excluded.sort_order;"
    )

# ---------- product images ----------
out += ["", "-- ===== product images (repo-relative paths; uploads will use Storage URLs) ====="]
for p in prods:
    slug = p["slug"]
    imgs = man.get(slug, [])
    if not imgs:
        continue
    # replace this product's image set wholesale so re-runs stay clean
    out.append(f"delete from public.store_product_images where product_id = "
               f"(select id from public.store_products where slug={q(slug)});")
    for j, im in enumerate(imgs):
        out.append(
            "insert into public.store_product_images (product_id,url,alt,sort_order) "
            f"select id,{q('images/products/' + im)},{q(p['name'])},{j} "
            f"from public.store_products where slug={q(slug)};"
        )

# ---------- pages ----------
PAGES = {
    "story":    "Our Story",
    "custom":   "Custom Heirlooms",
    "shipping": "Shipping & Returns",
    "contact":  "Contact",
}
out += ["", "-- ===== editable pages (body blocks are authored in the editor) ====="]
for key, title in PAGES.items():
    out.append(
        f"insert into public.store_pages (key,title,body) values ({q(key)},{q(title)},'[]'::jsonb)\n"
        "on conflict (key) do update set title=excluded.title;"
    )

# ---------- settings ----------
out += ["", "-- ===== settings ====="]
settings = {
    "tagline": "Limited-run and custom artifacts and jewelry designed, cast and finished by hand in California.",
    "hero_image": "assets/hero.png",
}
for k, val in settings.items():
    out.append(
        f"insert into public.store_settings (key,value) values ({q(k)},{q(json.dumps(val))}::jsonb)\n"
        "on conflict (key) do update set value=excluded.value;"
    )

out += ["", "commit;"]

open("seed-store.sql", "w", encoding="utf-8").write("\n".join(out) + "\n")
n_products = len([p for p in prods if man.get(p['slug'])])
n_images = sum(len(v) for v in man.values())
print(f"wrote seed-store.sql — {n_products} products, {n_images} images, "
      f"{len(PAGES)} pages, {len(settings)} settings")
