-- Studio Maçon — seed store content (generated by make_seed.py; safe to re-run)
-- Run AFTER schema-store.sql.

begin;

-- ===== products =====
insert into public.store_products (slug,name,price,description,notes,collection,status,quantity,sort_order) values ('pip','Pip',220,'Tiny keeper of tenderness. Proximity induces unexpected comfort; scholars remain blissfully baffled. Each totem is made to order; please allow up to two weeks for us to make Pip for you.','{"Solid bronze; Ombré patina","29 x 27 x 17 mm"}','perennial','live',null,0)
on conflict (slug) do update set name=excluded.name, price=excluded.price, description=excluded.description, notes=excluded.notes, sort_order=excluded.sort_order;
insert into public.store_products (slug,name,price,description,notes,collection,status,quantity,sort_order) values ('rebi','Rebi',220,'Exhibits fluid properties, perceived silhouette in flux. Researchers report heightened reflexes after handling. Each totem is made to order; please allow up to two weeks for us to make Rebi for you.','{"Solid bronze; Ombré patina","42 x 16 x 16 mm"}','perennial','live',null,1)
on conflict (slug) do update set name=excluded.name, price=excluded.price, description=excluded.description, notes=excluded.notes, sort_order=excluded.sort_order;
insert into public.store_products (slug,name,price,description,notes,collection,status,quantity,sort_order) values ('ren','Ren',220,'Steward of forgotten paths. Dawn light lingers unusually long upon golden mane. Each totem is made to order; please allow up to two weeks for us to make Ren for you.','{"Solid bronze; Ombré patina","40 x 37 x 13 mm"}','perennial','live',null,2)
on conflict (slug) do update set name=excluded.name, price=excluded.price, description=excluded.description, notes=excluded.notes, sort_order=excluded.sort_order;
insert into public.store_products (slug,name,price,description,notes,collection,status,quantity,sort_order) values ('zuma','Zuma',220,'Desert spirit present. Namesake ring awakens dormant essence; ancient runes suggest sacred link. Each totem is made to order; please allow up to two weeks for us to make Zuma for you.','{"Solid bronze; Ombré patina","38 x 25 x 13 mm"}','perennial','live',null,3)
on conflict (slug) do update set name=excluded.name, price=excluded.price, description=excluded.description, notes=excluded.notes, sort_order=excluded.sort_order;
insert into public.store_products (slug,name,price,description,notes,collection,status,quantity,sort_order) values ('ori','Ori',220,'Faithful guardian of the forests and rivers. Subtle warmth radiates during winter solstice. Each totem is made to order; please allow up to two weeks for us to make Ori for you.','{"Solid bronze; Ombré patina","35 x 21 x 19 mm"}','perennial','live',null,4)
on conflict (slug) do update set name=excluded.name, price=excluded.price, description=excluded.description, notes=excluded.notes, sort_order=excluded.sort_order;
insert into public.store_products (slug,name,price,description,notes,collection,status,quantity,sort_order) values ('yael','Yaël',220,'Inimitable poise suggests prophecy in metal. Mountaintop altar bells resonate in its presence. Each totem is made to order; please allow up to two weeks for us to make Yael for you.','{"Solid bronze; Ombré patina","30 x 22 x 11 mm"}','perennial','live',null,5)
on conflict (slug) do update set name=excluded.name, price=excluded.price, description=excluded.description, notes=excluded.notes, sort_order=excluded.sort_order;
insert into public.store_products (slug,name,price,description,notes,collection,status,quantity,sort_order) values ('zuma-ring','Zuma Ring',320,'Sand spirit distilled to sacred heirloom. Unearthed glyphs show evidence of rituals with paired totem. Each piece is made to order; please allow up to two weeks for us to make your Zuma Ring.','{"100% Sterling silver"}','perennial','live',null,6)
on conflict (slug) do update set name=excluded.name, price=excluded.price, description=excluded.description, notes=excluded.notes, sort_order=excluded.sort_order;
insert into public.store_products (slug,name,price,description,notes,collection,status,quantity,sort_order) values ('milo','Milo',220,'Ancient wanderer seeking home. Surface adapts to handler; bonds deepen with patina over time. Each totem is made to order; please allow up to two weeks for us to make Milo for you.','{"Solid bronze; Ombré patina","36 x 26 x 11 mm"}','perennial','live',null,7)
on conflict (slug) do update set name=excluded.name, price=excluded.price, description=excluded.description, notes=excluded.notes, sort_order=excluded.sort_order;
insert into public.store_products (slug,name,price,description,notes,collection,status,quantity,sort_order) values ('eclipse-ring','Eclipse Ring',340,'Asymmetric ellipses locked in patient equilibrium. The space between holds questions only stars can answer. Each piece is made to order; please allow up to two weeks for us to make your Eclipse Ring.','{"100% Sterling silver"}','perennial','live',null,8)
on conflict (slug) do update set name=excluded.name, price=excluded.price, description=excluded.description, notes=excluded.notes, sort_order=excluded.sort_order;
insert into public.store_products (slug,name,price,description,notes,collection,status,quantity,sort_order) values ('sietch-aperture','Sietch Ring',340,'Recovered from the wake of a passing comet. Aperture reveals oscillating presence of landscapes that do not appear on any map. Each piece is made to order; please allow up to two weeks for us to make your Sietch Ring for you.','{"100% Sterling silver"}','perennial','live',null,9)
on conflict (slug) do update set name=excluded.name, price=excluded.price, description=excluded.description, notes=excluded.notes, sort_order=excluded.sort_order;
insert into public.store_products (slug,name,price,description,notes,collection,status,quantity,sort_order) values ('lunar-canyon-ring','Lunar Canyon',370,'Sundered artifact forged from the core of a distant moon. Social gatherings reportedly ebb and flow in time with wearer''s presence. Each piece is made to order; please allow up to two weeks for us to make your Lunar Canyon Ring.','{"100% Sterling silver"}','perennial','live',null,10)
on conflict (slug) do update set name=excluded.name, price=excluded.price, description=excluded.description, notes=excluded.notes, sort_order=excluded.sort_order;
insert into public.store_products (slug,name,price,description,notes,collection,status,quantity,sort_order) values ('eleph','Eleph',220,'Breath suspended in solid bronze. Distant trumpeting reported by independent observers. Eleph is currently on preorder and will ship late April.','{"Solid bronze; Ombré patina","34 x 31 x 14 mm"}','perennial','live',null,11)
on conflict (slug) do update set name=excluded.name, price=excluded.price, description=excluded.description, notes=excluded.notes, sort_order=excluded.sort_order;
insert into public.store_products (slug,name,price,description,notes,collection,status,quantity,sort_order) values ('wonderhorn-talisman','Ida''s Wonder Horn',390,'Spiral resonator reveals undiscovered chords. Lab equipment vibrates sympathetically; nearby children develop perfect pitch. Each piece is made to order; please allow up to two weeks for us to make your Ida''s Wonder Horn.','{"100% Sterling silver, 30\" Chain"}','perennial','live',null,12)
on conflict (slug) do update set name=excluded.name, price=excluded.price, description=excluded.description, notes=excluded.notes, sort_order=excluded.sort_order;
insert into public.store_products (slug,name,price,description,notes,collection,status,quantity,sort_order) values ('macon-cap','Maçon Cap',50,'Tasteful cap adorned with mystic symbol. Offers modicum of solar protection.','{}','perennial','live',null,13)
on conflict (slug) do update set name=excluded.name, price=excluded.price, description=excluded.description, notes=excluded.notes, sort_order=excluded.sort_order;
insert into public.store_products (slug,name,price,description,notes,collection,status,quantity,sort_order) values ('ibi','Ibi',220,'Eternal watcher believed to guard ancestral secrets. Attempts to transmit likeness met with lens fog. Ibi is currently on preorder and will ship late April.','{"Solid bronze; Ombré patina","37 x 26 x 12 mm"}','perennial','live',null,14)
on conflict (slug) do update set name=excluded.name, price=excluded.price, description=excluded.description, notes=excluded.notes, sort_order=excluded.sort_order;
insert into public.store_products (slug,name,price,description,notes,collection,status,quantity,sort_order) values ('ear-cuff','Caldera Arc',260,'Perfect geometries betray cosmic provenance. Light fractures into otherworldy spectra across mirrored edge. Each piece is made to order; please allow up to two weeks for us to make your Caldera Arc.','{"100% Sterling silver"}','perennial','live',null,15)
on conflict (slug) do update set name=excluded.name, price=excluded.price, description=excluded.description, notes=excluded.notes, sort_order=excluded.sort_order;
insert into public.store_products (slug,name,price,description,notes,collection,status,quantity,sort_order) values ('starshipkey-pendant','Starship Key',460,'Elegant device of stellar origin. Prolonged exposure known to cause wanderlust; researchers &quot;forget&quot; to return. Each piece is made to order; please allow up to two weeks for us to make your Starship Key for you.','{"100% Sterling silver, 30\" chain"}','perennial','live',null,16)
on conflict (slug) do update set name=excluded.name, price=excluded.price, description=excluded.description, notes=excluded.notes, sort_order=excluded.sort_order;
insert into public.store_products (slug,name,price,description,notes,collection,status,quantity,sort_order) values ('meridian-egg-ring','Meridian Egg',390,'Weight exceeds material expectations. Metaphyiscal analysis detects abyss gazing back. Each piece is made to order; please allow up to two weeks for us to make your Meridian Egg.','{"100% Sterling silver"}','perennial','live',null,17)
on conflict (slug) do update set name=excluded.name, price=excluded.price, description=excluded.description, notes=excluded.notes, sort_order=excluded.sort_order;

-- ===== product images (repo-relative paths; uploads will use Storage URLs) =====
delete from public.store_product_images where product_id = (select id from public.store_products where slug='pip');
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/pip-1.jpg','Pip',0 from public.store_products where slug='pip';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/pip-2.jpg','Pip',1 from public.store_products where slug='pip';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/pip-3.jpg','Pip',2 from public.store_products where slug='pip';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/pip-4.jpg','Pip',3 from public.store_products where slug='pip';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/pip-5.jpg','Pip',4 from public.store_products where slug='pip';
delete from public.store_product_images where product_id = (select id from public.store_products where slug='rebi');
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/rebi-1.jpg','Rebi',0 from public.store_products where slug='rebi';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/rebi-2.jpg','Rebi',1 from public.store_products where slug='rebi';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/rebi-3.jpg','Rebi',2 from public.store_products where slug='rebi';
delete from public.store_product_images where product_id = (select id from public.store_products where slug='ren');
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/ren-1.jpg','Ren',0 from public.store_products where slug='ren';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/ren-2.jpg','Ren',1 from public.store_products where slug='ren';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/ren-3.jpg','Ren',2 from public.store_products where slug='ren';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/ren-4.jpg','Ren',3 from public.store_products where slug='ren';
delete from public.store_product_images where product_id = (select id from public.store_products where slug='zuma');
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/zuma-1.jpg','Zuma',0 from public.store_products where slug='zuma';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/zuma-2.jpg','Zuma',1 from public.store_products where slug='zuma';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/zuma-3.jpg','Zuma',2 from public.store_products where slug='zuma';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/zuma-4.jpg','Zuma',3 from public.store_products where slug='zuma';
delete from public.store_product_images where product_id = (select id from public.store_products where slug='ori');
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/ori-1.jpg','Ori',0 from public.store_products where slug='ori';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/ori-2.jpg','Ori',1 from public.store_products where slug='ori';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/ori-3.jpg','Ori',2 from public.store_products where slug='ori';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/ori-4.jpg','Ori',3 from public.store_products where slug='ori';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/ori-5.jpg','Ori',4 from public.store_products where slug='ori';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/ori-6.jpg','Ori',5 from public.store_products where slug='ori';
delete from public.store_product_images where product_id = (select id from public.store_products where slug='yael');
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/yael-1.jpg','Yaël',0 from public.store_products where slug='yael';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/yael-2.jpg','Yaël',1 from public.store_products where slug='yael';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/yael-3.jpg','Yaël',2 from public.store_products where slug='yael';
delete from public.store_product_images where product_id = (select id from public.store_products where slug='zuma-ring');
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/zuma-ring-1.jpg','Zuma Ring',0 from public.store_products where slug='zuma-ring';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/zuma-ring-2.jpg','Zuma Ring',1 from public.store_products where slug='zuma-ring';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/zuma-ring-3.jpg','Zuma Ring',2 from public.store_products where slug='zuma-ring';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/zuma-ring-4.jpg','Zuma Ring',3 from public.store_products where slug='zuma-ring';
delete from public.store_product_images where product_id = (select id from public.store_products where slug='milo');
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/milo-1.jpg','Milo',0 from public.store_products where slug='milo';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/milo-2.jpg','Milo',1 from public.store_products where slug='milo';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/milo-3.jpg','Milo',2 from public.store_products where slug='milo';
delete from public.store_product_images where product_id = (select id from public.store_products where slug='eclipse-ring');
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/eclipse-ring-1.jpg','Eclipse Ring',0 from public.store_products where slug='eclipse-ring';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/eclipse-ring-2.jpg','Eclipse Ring',1 from public.store_products where slug='eclipse-ring';
delete from public.store_product_images where product_id = (select id from public.store_products where slug='sietch-aperture');
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/sietch-aperture-1.jpg','Sietch Ring',0 from public.store_products where slug='sietch-aperture';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/sietch-aperture-2.jpg','Sietch Ring',1 from public.store_products where slug='sietch-aperture';
delete from public.store_product_images where product_id = (select id from public.store_products where slug='lunar-canyon-ring');
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/lunar-canyon-ring-1.jpg','Lunar Canyon',0 from public.store_products where slug='lunar-canyon-ring';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/lunar-canyon-ring-2.jpg','Lunar Canyon',1 from public.store_products where slug='lunar-canyon-ring';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/lunar-canyon-ring-3.jpg','Lunar Canyon',2 from public.store_products where slug='lunar-canyon-ring';
delete from public.store_product_images where product_id = (select id from public.store_products where slug='eleph');
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/eleph-1.jpg','Eleph',0 from public.store_products where slug='eleph';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/eleph-2.jpg','Eleph',1 from public.store_products where slug='eleph';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/eleph-3.jpg','Eleph',2 from public.store_products where slug='eleph';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/eleph-4.jpg','Eleph',3 from public.store_products where slug='eleph';
delete from public.store_product_images where product_id = (select id from public.store_products where slug='wonderhorn-talisman');
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/wonderhorn-talisman-1.jpg','Ida''s Wonder Horn',0 from public.store_products where slug='wonderhorn-talisman';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/wonderhorn-talisman-2.jpg','Ida''s Wonder Horn',1 from public.store_products where slug='wonderhorn-talisman';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/wonderhorn-talisman-3.jpg','Ida''s Wonder Horn',2 from public.store_products where slug='wonderhorn-talisman';
delete from public.store_product_images where product_id = (select id from public.store_products where slug='macon-cap');
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/macon-cap-1.jpg','Maçon Cap',0 from public.store_products where slug='macon-cap';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/macon-cap-2.jpg','Maçon Cap',1 from public.store_products where slug='macon-cap';
delete from public.store_product_images where product_id = (select id from public.store_products where slug='ibi');
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/ibi-1.jpg','Ibi',0 from public.store_products where slug='ibi';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/ibi-2.jpg','Ibi',1 from public.store_products where slug='ibi';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/ibi-3.jpg','Ibi',2 from public.store_products where slug='ibi';
delete from public.store_product_images where product_id = (select id from public.store_products where slug='ear-cuff');
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/ear-cuff-1.jpg','Caldera Arc',0 from public.store_products where slug='ear-cuff';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/ear-cuff-2.jpg','Caldera Arc',1 from public.store_products where slug='ear-cuff';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/ear-cuff-3.jpg','Caldera Arc',2 from public.store_products where slug='ear-cuff';
delete from public.store_product_images where product_id = (select id from public.store_products where slug='starshipkey-pendant');
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/starshipkey-pendant-1.jpg','Starship Key',0 from public.store_products where slug='starshipkey-pendant';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/starshipkey-pendant-2.jpg','Starship Key',1 from public.store_products where slug='starshipkey-pendant';
delete from public.store_product_images where product_id = (select id from public.store_products where slug='meridian-egg-ring');
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/meridian-egg-ring-1.jpg','Meridian Egg',0 from public.store_products where slug='meridian-egg-ring';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/meridian-egg-ring-2.jpg','Meridian Egg',1 from public.store_products where slug='meridian-egg-ring';
insert into public.store_product_images (product_id,url,alt,sort_order) select id,'images/products/meridian-egg-ring-3.jpg','Meridian Egg',2 from public.store_products where slug='meridian-egg-ring';

-- ===== editable pages (body blocks are authored in the editor) =====
insert into public.store_pages (key,title,body) values ('story','Our Story','[]'::jsonb)
on conflict (key) do update set title=excluded.title;
insert into public.store_pages (key,title,body) values ('custom','Custom Heirlooms','[]'::jsonb)
on conflict (key) do update set title=excluded.title;
insert into public.store_pages (key,title,body) values ('shipping','Shipping & Returns','[]'::jsonb)
on conflict (key) do update set title=excluded.title;
insert into public.store_pages (key,title,body) values ('contact','Contact','[]'::jsonb)
on conflict (key) do update set title=excluded.title;

-- ===== settings =====
insert into public.store_settings (key,value) values ('tagline','"Limited-run and custom artifacts and jewelry designed, cast and finished by hand in California."'::jsonb)
on conflict (key) do update set value=excluded.value;
insert into public.store_settings (key,value) values ('hero_image','"assets/hero.png"'::jsonb)
on conflict (key) do update set value=excluded.value;

commit;
