-- tag which product photos are 'in hand' vs plain (generated; safe to re-run)
alter table public.store_product_images
  add column if not exists variant text
  check (variant in ('hand','plain') or variant is null);

begin;
update public.store_product_images set variant='hand' where url like '%ear-cuff-1.jpg';
update public.store_product_images set variant='plain' where url like '%ear-cuff-2.jpg';
update public.store_product_images set variant='hand' where url like '%ear-cuff-3.jpg';
update public.store_product_images set variant='hand' where url like '%eclipse-ring-1.jpg';
update public.store_product_images set variant='plain' where url like '%eclipse-ring-2.jpg';
update public.store_product_images set variant='plain' where url like '%eleph-1.jpg';
update public.store_product_images set variant='hand' where url like '%eleph-2.jpg';
update public.store_product_images set variant='plain' where url like '%eleph-3.jpg';
update public.store_product_images set variant='plain' where url like '%eleph-4.jpg';
update public.store_product_images set variant='hand' where url like '%ibi-1.jpg';
update public.store_product_images set variant='plain' where url like '%ibi-2.jpg';
update public.store_product_images set variant='plain' where url like '%ibi-3.jpg';
update public.store_product_images set variant='plain' where url like '%lunar-canyon-ring-1.jpg';
update public.store_product_images set variant='hand' where url like '%lunar-canyon-ring-2.jpg';
update public.store_product_images set variant='plain' where url like '%lunar-canyon-ring-3.jpg';
update public.store_product_images set variant='plain' where url like '%macon-cap-1.jpg';
update public.store_product_images set variant='plain' where url like '%macon-cap-2.jpg';
update public.store_product_images set variant='plain' where url like '%meridian-egg-ring-1.jpg';
update public.store_product_images set variant='hand' where url like '%meridian-egg-ring-2.jpg';
update public.store_product_images set variant='plain' where url like '%meridian-egg-ring-3.jpg';
update public.store_product_images set variant='plain' where url like '%milo-1.jpg';
update public.store_product_images set variant='hand' where url like '%milo-2.jpg';
update public.store_product_images set variant='plain' where url like '%milo-3.jpg';
update public.store_product_images set variant='hand' where url like '%ori-1.jpg';
update public.store_product_images set variant='plain' where url like '%ori-2.jpg';
update public.store_product_images set variant='plain' where url like '%ori-3.jpg';
update public.store_product_images set variant='plain' where url like '%ori-4.jpg';
update public.store_product_images set variant='plain' where url like '%ori-5.jpg';
update public.store_product_images set variant='plain' where url like '%ori-6.jpg';
update public.store_product_images set variant='hand' where url like '%pip-1.jpg';
update public.store_product_images set variant='plain' where url like '%pip-2.jpg';
update public.store_product_images set variant='plain' where url like '%pip-3.jpg';
update public.store_product_images set variant='plain' where url like '%pip-4.jpg';
update public.store_product_images set variant='plain' where url like '%pip-5.jpg';
update public.store_product_images set variant='plain' where url like '%rebi-1.jpg';
update public.store_product_images set variant='hand' where url like '%rebi-2.jpg';
update public.store_product_images set variant='plain' where url like '%rebi-3.jpg';
update public.store_product_images set variant='plain' where url like '%ren-1.jpg';
update public.store_product_images set variant='hand' where url like '%ren-2.jpg';
update public.store_product_images set variant='plain' where url like '%ren-3.jpg';
update public.store_product_images set variant='plain' where url like '%ren-4.jpg';
update public.store_product_images set variant='plain' where url like '%sietch-aperture-1.jpg';
update public.store_product_images set variant='plain' where url like '%sietch-aperture-2.jpg';
update public.store_product_images set variant='plain' where url like '%starshipkey-pendant-1.jpg';
update public.store_product_images set variant='plain' where url like '%starshipkey-pendant-2.jpg';
update public.store_product_images set variant='plain' where url like '%wonderhorn-talisman-1.jpg';
update public.store_product_images set variant='plain' where url like '%wonderhorn-talisman-2.jpg';
update public.store_product_images set variant='plain' where url like '%wonderhorn-talisman-3.jpg';
update public.store_product_images set variant='hand' where url like '%yael-1.jpg';
update public.store_product_images set variant='plain' where url like '%yael-2.jpg';
update public.store_product_images set variant='plain' where url like '%yael-3.jpg';
update public.store_product_images set variant='plain' where url like '%zuma-1.jpg';
update public.store_product_images set variant='hand' where url like '%zuma-2.jpg';
update public.store_product_images set variant='plain' where url like '%zuma-3.jpg';
update public.store_product_images set variant='plain' where url like '%zuma-4.jpg';
update public.store_product_images set variant='hand' where url like '%zuma-ring-1.jpg';
update public.store_product_images set variant='plain' where url like '%zuma-ring-2.jpg';
update public.store_product_images set variant='plain' where url like '%zuma-ring-3.jpg';
update public.store_product_images set variant='plain' where url like '%zuma-ring-4.jpg';
commit;
